import "./globals.css";
import Link from "next/link";
import Navbar from "./_components/Navbar";
import { inter } from "./ui/fonts";
import AnimatedCursor from "react-animated-cursor";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en" className="">
			<body className={`${inter.className} antialiased`}>
				<AnimatedCursor
					innerSize={8}
					outerSize={35}
					innerScale={1}
					outerScale={2}
					outerAlpha={0}
					hasBlendMode={true}
					innerStyle={{
						backgroundColor: "var(--cursor-color)",
					}}
					outerStyle={{
						border: "3px solid var(--cursor-color)",
					}}
				/>
				<Navbar />
				{children}
			</body>
		</html>
	);
}
