import "./globals.css";
import Link from "next/link";
import Navbar from "./_components/Navbar";
import { inter } from "./ui/fonts";
import { Providers } from "./providers";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en" className="">
			<body className={`${inter.className} antialiased`}>
				<Providers>
					<Navbar />
					{children}
				</Providers>
			</body>
		</html>
	);
}
